version: '3'
services:
  quantum:
    build: ./
    image: quantum
    container_name: quantum
    environment:
      QUANTUM_FB_APP_ID: ${QUANTUM_FB_APP_ID}
      QUANTUM_FB_APP_SECRET: ${QUANTUM_FB_APP_SECRET}
      QUANTUM_FB_ACCESS_TOKEN: ${QUANTUM_FB_ACCESS_TOKEN}
      QUANTUM_TWITTER_CONSUMER_KEY: ${QUANTUM_TWITTER_CONSUMER_KEY}
      QUANTUM_TWITTER_CONSUMER_SECRET: ${QUANTUM_TWITTER_CONSUMER_SECRET}
      QUANTUM_TWITTER_ACCESS_TOKEN: ${QUANTUM_TWITTER_ACCESS_TOKEN}
      QUANTUM_TWITTER_ACCESS_TOKEN_SECRET: ${QUANTUM_TWITTER_ACCESS_TOKEN_SECRET}
    ports:
      - "8080:8080"

