apiVersion: v1
kind: ConfigMap
metadata:
  name: quantum-configmap-boxer
  namespace: default
data:
  QUANTUM_BRAND: "Boxer"
  QUANTUM_FB_PAGE: boxersverige
  QUANTUM_TWITTER_QUERIES: #BoxerSverige;@boxersverige;BoxerSverige;to:BoxerSverige;from:BoxerSverige