apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: quantum-deployment-boxer
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: quantum-boxer
    spec:
      containers:
      - name: quantum-boxer
        image: mimerdevcontainerregistry.azurecr.io/quantum:b5422929
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: quantum-secrets-boxer
        - configMapRef:
            name: quantum-configmap-boxer
