package se.comhem.quantum.feed.twitter;

import se.comhem.quantum.feed.FeedDto;
import se.comhem.quantum.feed.PostDto;

import java.util.Collections;

import static java.util.Arrays.asList;

public class FeedMock {

    static FeedDto getFeedDtoMOCK() {
        return FeedDto.builder()
                .singles(asList(
                        PostDto.builder()
                                .message("inlägg utan kommentar")
                                .author("Ella eliasson")
                                .id(234L)
                                .authorImg("https://pbs.twimg.com/profile_images/852492247224520705/P1iDZA9a_400x400.jpg")
                                .date("2017-02-01")
                                .plattform("TWITTER")
                                .city("stockholm")
                                .location(asList(64.0, 15.0))
                                .build(),
                        PostDto.builder()
                                .message("inlägg utan kommentarinlägg utan kommentarinlägg utan kommentarinlägg utan kommentarinlägg utan kommentar")
                                .author("Ella eliasson")
                                .id(234L)
                                .authorImg("https://pbs.twimg.com/profile_images/852492247224520705/P1iDZA9a_400x400.jpg")
                                .date("2017-02-01")
                                .location(asList(60.0, 16.0))
                                .plattform("TWITTER")
                                .build(),
                        PostDto.builder()
                                .message("inlägg2 utan kommentar")
                                .author("rogge Jönsson")
                                .id(234L)
                                .date("2017-02-01")
                                .location(asList(66.0, 16.0))
                                .authorImg("https://pbs.twimg.com/profile_images/852492247224520705/P1iDZA9a_400x400.jpg")
                                .plattform("TWITTER")
                                .build(),
                        PostDto.builder()
                                .message("inlägg utan kommentar")
                                .author("Ella eliasson")
                                .id(234L)
                                .authorImg("https://pbs.twimg.com/profile_images/852492247224520705/P1iDZA9a_400x400.jpg")
                                .date("2017-02-01")
                                .plattform("TWITTER")
                                .build(),
                        PostDto.builder()
                                .message("inlägg utan kommentarinlägg utan kommentarinlägg utan kommentarinlägg utan kommentarinlägg utan kommentar")
                                .author("Ella eliasson")
                                .id(234L)
                                .authorImg("https://pbs.twimg.com/profile_images/852492247224520705/P1iDZA9a_400x400.jpg")
                                .date("2017-02-01")
                                .plattform("TWITTER")
                                .build(),
                        PostDto.builder()
                                .message("inlägg2 utan kommentar")
                                .author("rogge Jönsson")
                                .id(234L)
                                .date("2017-02-01")
                                .authorImg("https://pbs.twimg.com/profile_images/852492247224520705/P1iDZA9a_400x400.jpg")
                                .plattform("TWITTER")
                                .build(),
                        PostDto.builder()
                                .message("inlägg utan kommentarinlägg utan kommentarinlägnlägg utan kommentarinlägg utan kommentarinlägnlägg utan kommentarinlägg utan kommentarinlägnlägg utan kommentarinlägg utan kommentarinlägnlägg utan kommentarinlägg utan kommentarinlägnlägg utan kommentarinlägg utan kommentarinlägnlägg utan kommentarinlägg utan kommentarinlägnlägg utan kommentarinlägg utan kommentarinlägnlägg utan kommentarinlägg utan kommentarinlägnlägg utan kommentarinlägg utan kommentarinlägnlägg utan kommentarinlägg utan kommentarinlägnlägg utan kommentarinlägg utan kommentarinlägnlägg utan kommentarinlägg utan kommentarinlägnlägg utan kommentarinlägg utan kommentarinlägnlägg utan kommentarinlägg utan kommentarinlägnlägg utan kommentarinlägg utan kommentarinlägnlägg utan kommentarinlägg utan kommentarinlägnlägg utan kommentarinlägg utan kommentarinlägnlägg utan kommentarinlägg utan kommentarinlägnlägg utan kommentarinlägg utan kommentarinlägg utan kommentarinlägg utan kommentarinlägg utan kommentar")
                                .author("Ella eliasson")
                                .id(234L)
                                .authorImg("https://pbs.twimg.com/profile_images/852492247224520705/P1iDZA9a_400x400.jpg")
                                .date("2017-02-01")
                                .plattform("TWITTER")
                                .location(asList(66.0, 16.0))
                                .build(),
                        PostDto.builder()
                                .message("inlägg2 utan kommentar")
                                .author("rogge Jönsson")
                                .id(234L)
                                .date("2017-02-01")
                                .authorImg("https://pbs.twimg.com/profile_images/852492247224520705/P1iDZA9a_400x400.jpg")
                                .plattform("TWITTER")
                                .build(),
                        PostDto.builder()
                                .message("inlägg2mentar")
                                .author("rogge Jönsson")
                                .id(234L)
                                .date("2017-02-01")
                                .authorImg("https://pbs.twimg.com/profile_images/852492247224520705/P1iDZA9a_400x400.jpg")
                                .plattform("TWITTER")
                                .build(),
                        PostDto.builder()
                                .message("inlägg2 utan kommentar")
                                .author("rogge Jönsson")
                                .id(234L)
                                .location(asList(60.0, 11.0))
                                .date("2017-02-01")
                                .authorImg("https://pbs.twimg.com/profile_images/852492247224520705/P1iDZA9a_400x400.jpg")
                                .plattform("TWITTER")
                                .build(),
                        PostDto.builder()
                                .message("inlägg utan kommentarinlägg utan kommentarinlägnlägg utan kommentarinlägg utan kommentarinlägnlägg utan kommentarinlägg utan kommentarinlägnlägg utan kommentarinlägg utan kommentarinlägnlägg utan kommentarinlägg utan kommentarinlägnlägg utan kommentarinlägg utan kommentarinlägnlägg utan kommentarinlägg utan kommentarinlägnlägg utan kommentarinlägg utan kommentarinlägnlägg utan kommentarinlägg utan kommentarinlägnlägg utan kommentarinlägg utan kommentarinlägnlägg utan kommentarinlägg utan kommentarinlägnlägg utan kommentarinlägg utan kommentarinlägnlägg utan kommentarinlägg utan kommentarinlägnlägg utan kommentarinlägg utan kommentarinlägnlägg utan kommentarinlägg utan kommentarinlägnlägg utan kommentarinlägg utan kommentarinlägnlägg utan kommentarinlägg utan kommentarinlägnlägg utan kommentarinlägg utan kommentarinlägnlägg utan kommentarinlägg utan kommentarinlägnlägg utan kommentarinlägg utan kommentarinlägg utan kommentarinlägg utan kommentarinlägg utan kommentar")
                                .author("Ella eliasson")
                                .id(234L)
                                .authorImg("https://pbs.twimg.com/profile_images/852492247224520705/P1iDZA9a_400x400.jpg")
                                .date("2017-02-01")
                                .plattform("TWITTER")
                                .build(),
                        PostDto.builder()
                                .message("inlägg2 utan kommentar")
                                .author("rogge Jönsson")
                                .id(234L)
                                .date("2017-02-01")
                                .authorImg("https://pbs.twimg.com/profile_images/852492247224520705/P1iDZA9a_400x400.jpg")
                                .plattform("TWITTER")
                                .build(),
                        PostDto.builder()
                                .message("inlägg2mentar")
                                .author("rogge Jönsson")
                                .id(234L)
                                .date("2017-02-01")
                                .authorImg("https://pbs.twimg.com/profile_images/852492247224520705/P1iDZA9a_400x400.jpg")
                                .plattform("TWITTER")
                                .build()

                )).threads(asList(
                        PostDto.builder()
                                .message("inlägg om smågrodor med kommentar")
                                .author("Ella eliasson")
                                .authorImg("https://pbs.twimg.com/profile_images/852492247224520705/P1iDZA9a_400x400.jpg")
                                .id(234L)
                                .replies(asList(
                                        PostDto.builder()
                                                .message("toplevel med kommentar")
                                                .author("rogge Jönsson")
                                                .id(234L)
                                                .replies(asList(PostDto.builder()
                                                        .message("inss till toplevel")
                                                        .author("rogge Jönsson")
                                                        .id(234L)
                                                        .location(asList(61.0, 16.0))
                                                        .replies(Collections.emptyList())
                                                        .plattform("TWITTER")
                                                        .build()))
                                                .plattform("TWITTER")
                                                .build(),

                                        PostDto.builder()
                                                .message("COMMENT inlägg om smågrodor med kommentar")
                                                .author("rogge Jönsson")
                                                .id(234L)
                                                .replies(asList(PostDto.builder()
                                                        .message("COMMENT nr 2 inlägg om smågrodor med kommentar")
                                                        .author("rogge Jönsson")
                                                        .id(234L)
                                                        .replies(asList(PostDto.builder()
                                                                .message("qrewfq43g534g55ftw4t till smågrodor")
                                                                .author("rogge Jönsson")
                                                                .id(234L)
                                                                .location(asList(65.0, 16.0))
                                                                .replies(asList(PostDto.builder()
                                                                        .message("qrewfq43g534g55ftw4t till smågrodor")
                                                                        .author("rogge Jönsson")
                                                                        .id(234L)
                                                                        .replies(asList(PostDto.builder()
                                                                                .message("qrewfq43g534g55ftw4t till smågrodor")
                                                                                .author("rogge Jönsson")
                                                                                .id(234L)
                                                                                .replies(asList(PostDto.builder()
                                                                                        .message("qrewfq43g534g55ftw4t till smågrodor")
                                                                                        .author("rogge Jönsson")
                                                                                        .id(234L)
                                                                                        .replies(Collections.emptyList())
                                                                                        .plattform("TWITTER")
                                                                                        .build()))
                                                                                .plattform("TWITTER")
                                                                                .build()))
                                                                        .plattform("TWITTER")
                                                                        .build()))
                                                                .plattform("TWITTER")
                                                                .build()))
                                                        .plattform("TWITTER")
                                                        .build()))
                                                .plattform("TWITTER")
                                                .build()))
                                .plattform("TWITTER")
                                .build(),
                        PostDto.builder()
                                .message("inlägg om smågrodor med kommentar")
                                .author("Ella eliasson")
                                .authorImg("https://pbs.twimg.com/profile_images/852492247224520705/P1iDZA9a_400x400.jpg")
                                .id(234L)

                                .replies(asList(
                                        PostDto.builder()
                                                .message("toplevel med kommentar")
                                                .author("rogge Jönsson")
                                                .id(234L)
                                                .replies(asList(PostDto.builder()
                                                        .message("inss till toplevel")
                                                        .author("rogge Jönsson")
                                                        .id(234L)
                                                        .replies(Collections.emptyList())
                                                        .plattform("TWITTER")
                                                        .build()))
                                                .plattform("TWITTER")
                                                .build(),

                                        PostDto.builder()
                                                .message("COMMENT inlägg om smågrodor med kommentar")
                                                .author("rogge Jönsson")
                                                .id(234L)
                                                .replies(asList(PostDto.builder()
                                                        .message("COMMENT nr 2 inlägg om smågrodor med kommentar")
                                                        .author("rogge Jönsson")
                                                        .id(234L)
                                                        .replies(asList(PostDto.builder()
                                                                .message("qrewfq43g534g55ftw4t till smågrodor")
                                                                .author("rogge Jönsson")
                                                                .id(234L)
                                                                .replies(asList(PostDto.builder()
                                                                        .message("qrewfq43g534g55ftw4t till smågrodor")
                                                                        .author("rogge Jönsson")
                                                                        .id(234L)
                                                                        .replies(asList(PostDto.builder()
                                                                                .message("qrewfq43g534g55ftw4t till smågrodor")
                                                                                .author("rogge Jönsson")
                                                                                .id(234L)
                                                                                .replies(asList(PostDto.builder()
                                                                                        .message("qrewfq43g534g55ftw4t till smågrodor")
                                                                                        .author("rogge Jönsson")
                                                                                        .id(234L)
                                                                                        .replies(Collections.emptyList())
                                                                                        .plattform("TWITTER")
                                                                                        .build()))
                                                                                .plattform("TWITTER")
                                                                                .build()))
                                                                        .plattform("TWITTER")
                                                                        .build()))
                                                                .plattform("TWITTER")
                                                                .build()))
                                                        .plattform("TWITTER")
                                                        .build()))
                                                .plattform("TWITTER")
                                                .build()))
                                .plattform("TWITTER")
                                .build(),
                        PostDto.builder()
                                .message("inlägg om smågrodor med kommentar")
                                .author("Ella eliasson")
                                .authorImg("https://pbs.twimg.com/profile_images/852492247224520705/P1iDZA9a_400x400.jpg")
                                .id(234L)
                                .replies(asList(
                                        PostDto.builder()
                                                .message("toplevel med kommentar")
                                                .author("rogge Jönsson")
                                                .id(234L)
                                                .replies(asList(PostDto.builder()
                                                        .message("inss till toplevel")
                                                        .author("rogge Jönsson")
                                                        .id(234L)
                                                        .replies(Collections.emptyList())
                                                        .plattform("TWITTER")
                                                        .build()))
                                                .plattform("TWITTER")
                                                .build(),

                                        PostDto.builder()
                                                .message("COMMENT inlägg om smågrodor med kommentar")
                                                .author("rogge Jönsson")
                                                .id(234L)
                                                .replies(asList(PostDto.builder()
                                                        .message("COMMENT nr 2 inlägg om smågrodor med kommentar")
                                                        .author("rogge Jönsson")
                                                        .id(234L)
                                                        .replies(asList(PostDto.builder()
                                                                .message("qrewfq43g534g55ftw4t till smågrodor")
                                                                .author("rogge Jönsson")
                                                                .id(234L)
                                                                .replies(asList(PostDto.builder()
                                                                        .message("qrewfq43g534g55ftw4t till smågrodor")
                                                                        .author("rogge Jönsson")
                                                                        .id(234L)
                                                                        .replies(asList(PostDto.builder()
                                                                                .message("qrewfq43g534g55ftw4t till smågrodor")
                                                                                .author("rogge Jönsson")
                                                                                .id(234L)
                                                                                .replies(asList(PostDto.builder()
                                                                                        .message("qrewfq43g534g55ftw4t till smågrodor")
                                                                                        .author("rogge Jönsson")
                                                                                        .id(234L)
                                                                                        .replies(Collections.emptyList())
                                                                                        .plattform("TWITTER")
                                                                                        .build()))
                                                                                .plattform("TWITTER")
                                                                                .build()))
                                                                        .plattform("TWITTER")
                                                                        .build()))
                                                                .plattform("TWITTER")
                                                                .build()))
                                                        .plattform("TWITTER")
                                                        .build()))
                                                .plattform("TWITTER")
                                                .build()))
                                .plattform("TWITTER")
                                .build(),
                        PostDto.builder()
                                .message("inlägg om smågrodor med kommentar")
                                .author("Ella eliasson")
                                .authorImg("https://pbs.twimg.com/profile_images/852492247224520705/P1iDZA9a_400x400.jpg")
                                .id(234L)
                                .replies(asList(
                                        PostDto.builder()
                                                .message("toplevel med kommentar")
                                                .author("rogge Jönsson")
                                                .id(234L)
                                                .replies(asList(PostDto.builder()
                                                        .message("inss till toplevel")
                                                        .author("rogge Jönsson")
                                                        .id(234L)
                                                        .replies(Collections.emptyList())
                                                        .plattform("TWITTER")
                                                        .build()))
                                                .plattform("TWITTER")
                                                .build(),

                                        PostDto.builder()
                                                .message("COMMENT inlägg om smågrodor med kommentar")
                                                .author("rogge Jönsson")
                                                .id(234L)
                                                .replies(asList(PostDto.builder()
                                                        .message("COMMENT nr 2 inlägg om smågrodor med kommentar")
                                                        .author("rogge Jönsson")
                                                        .id(234L)
                                                        .replies(asList(PostDto.builder()
                                                                .message("qrewfq43g534g55ftw4t till smågrodor")
                                                                .author("rogge Jönsson")
                                                                .id(234L)
                                                                .replies(asList(PostDto.builder()
                                                                        .message("qrewfq43g534g55ftw4t till smågrodor")
                                                                        .author("rogge Jönsson")
                                                                        .id(234L)
                                                                        .replies(asList(PostDto.builder()
                                                                                .message("qrewfq43g534g55ftw4t till smågrodor")
                                                                                .author("rogge Jönsson")
                                                                                .id(234L)
                                                                                .replies(asList(PostDto.builder()
                                                                                        .message("qrewfq43g534g55ftw4t till smågrodor")
                                                                                        .author("rogge Jönsson")
                                                                                        .id(234L)
                                                                                        .replies(Collections.emptyList())
                                                                                        .plattform("TWITTER")
                                                                                        .build()))
                                                                                .plattform("TWITTER")
                                                                                .build()))
                                                                        .plattform("TWITTER")
                                                                        .build()))
                                                                .plattform("TWITTER")
                                                                .build()))
                                                        .plattform("TWITTER")
                                                        .build()))
                                                .plattform("TWITTER")
                                                .build()))
                                .plattform("TWITTER")
                                .build(),
                        PostDto.builder()
                                .message("inlägg om smågrodor med kommentar")
                                .author("Ella eliasson")
                                .authorImg("https://pbs.twimg.com/profile_images/852492247224520705/P1iDZA9a_400x400.jpg")
                                .id(234L)
                                .replies(asList(
                                        PostDto.builder()
                                                .message("toplevel med kommentar")
                                                .author("rogge Jönsson")
                                                .id(234L)
                                                .replies(asList(PostDto.builder()
                                                        .message("inss till toplevel")
                                                        .author("rogge Jönsson")
                                                        .id(234L)
                                                        .replies(Collections.emptyList())
                                                        .plattform("TWITTER")
                                                        .build()))
                                                .plattform("TWITTER")
                                                .build(),

                                        PostDto.builder()
                                                .message("COMMENT inlägg om smågrodor med kommentar")
                                                .author("rogge Jönsson")
                                                .id(234L)
                                                .replies(asList(PostDto.builder()
                                                        .message("COMMENT nr 2 inlägg om smågrodor med kommentar")
                                                        .author("rogge Jönsson")
                                                        .id(234L)
                                                        .replies(asList(PostDto.builder()
                                                                .message("qrewfq43g534g55ftw4t till smågrodor")
                                                                .author("rogge Jönsson")
                                                                .id(234L)
                                                                .replies(asList(PostDto.builder()
                                                                        .message("qrewfq43g534g55ftw4t till smågrodor")
                                                                        .author("rogge Jönsson")
                                                                        .id(234L)
                                                                        .replies(asList(PostDto.builder()
                                                                                .message("qrewfq43g534g55ftw4t till smågrodor")
                                                                                .author("rogge Jönsson")
                                                                                .id(234L)
                                                                                .replies(asList(PostDto.builder()
                                                                                        .message("qrewfq43g534g55ftw4t till smågrodor")
                                                                                        .author("rogge Jönsson")
                                                                                        .id(234L)
                                                                                        .replies(Collections.emptyList())
                                                                                        .plattform("TWITTER")
                                                                                        .build()))
                                                                                .plattform("TWITTER")
                                                                                .build()))
                                                                        .plattform("TWITTER")
                                                                        .build()))
                                                                .plattform("TWITTER")
                                                                .build()))
                                                        .plattform("TWITTER")
                                                        .build()))
                                                .plattform("TWITTER")
                                                .build()))
                                .plattform("TWITTER")
                                .build()))
                .build();
    }
}
